sudo: false
language: node_js
node_js:
- 14
before_install:
- npm install codecov.io coveralls
after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - master
script:
- npm run lint
- npm test
deploy:
  provider: npm
  api_key:
    secure: JkMB32WZiBXO9ZxEnns/qBbwmLZ7F8H7UL9j7VNBYvsHFv5A9Y35Cv0SOVaLfSTLDgzEbtQmwrreNPVtkrnocb8M8ojDiKJmNRE8zJ7dRMBE9pBde3WKkQN7uny4Vtjt/szSRFBuxcBp2iRzf7ONEpcnxwUMN99CIU5BUmivyNk/kU6lL4HbdM/DhoQ+zV/OF5fRCF1CGXL0jqNx9A4wP/+LMmEx4bqU54y86qqJrBxq9Xrvc4E3/+vMpcl9QYuBW20VxMZceBxw59rAYjF/ugFxHq+edP2fLUwc+7HIxHPBsgWu2ZERlEkhmxyZV91+o1S2M3k/jjNDqxsXd/7IDPhyYht6HCo4eJXQBwz3CPW6w73HSznu2flyKQghLEg03rRxL4sbs+6YGzNkPftTzHqH/1/5HjS5b1ap0mY/yh0AShdm7g/rI6zukcnJAQDV5U0kJrA0QZcXVxzSOzjuaOVI55fC6qn63WItIrN0T8K9SCuRzEYsIhSSQTx3Vh+VpfDqy3eZXgBeHReeudqTaknBvd4RAYYBcLIeIhJs3Wsb4mUQ3tP8Pg8xuoMvWZtsTksbJDYoqPW3T4U28rrflC3AtR4R/gx6ug0qOGWAWGSVT6ROh7sKATlvbjF5BdE9vXifyf1zbNHXztLVocue1U9rayP8naGw2xm9O5/GGw0=
  email:
    secure: PZZVWI0xJFNMCftloAPuBrIgKq4DgDl3Exb016H7UuheK+pt1aQsPVtNZaUEgJLKUS2ePC+s9Jnck7mBf94IMOND5P+m3MUfrtCnjI0j2NN+inWhw7B/h6PksOKSgbbGJGVCsINuv5CEjdWu61teD2tv4aELMZB5yf1z1dacARb943/BdxDgwr6PSNRrQz5pB5xsTXfn31lywWMLVogkX1pOoshWvqVTT6Ou4oAAKClupX8ZcDK2CrqKOKxrcfJiTdESmUhkQfWKTspkF/Nd3Ll8TLHZAqk5e2uyA/aI7FH6HvguStdGv9z95xvYulD3TY+BAIXmUt6AYviBPLZUtgA76ceIhPunpPfQhzBA+bUxtNNx7kDSbjCgaoHlitR8+w/Fa9j7a0c6pbCoGesZlMeleDewveY/2rYqgA/RqO+PMKilTB3P23FuheowMnYauZ9mjhRGQftuggVZ1MUJHVjUPCCCwRU/TKw1BLsKRuOPKCkkZ43Z9l93UvGfaSp3llUGHesVDeifKuR3YCF/h4V2PtlyYKiCNaJOaNS0h4fRkeujbevCABUAup7qKyptHOfn3+3/3jwNjTdp1luxBMooUYSxgeWQBncYNGUba1JNxejLpGNv1DVab1pTKRSlrQO5J2ZLeTFrP5Ob0tnocw8eYNGMfsvYMX7RZYtzK1k=
  on:
    branch: master
